# Generated by Django 4.0.2 on 2022-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma_tech', '0003_candhire_institute_vacancy_remove_candidate_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
