# Generated by Django 4.0.2 on 2022-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamma_tech', '0004_alter_candidate_phone_alter_institute_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cur_sal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exp_sal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
